image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - tags
  except:
    - branches

deploy:
  image: lwolf/kubectl_deployer:latest
  stage: deploy
  script:
    - sed -i "s/IMAGE_TAG/"${CI_COMMIT_TAG}"/g" controller.yml
    - kubectl --namespace=imageoptimizer apply -f controller.yml
  only:
    - tags
  except:
    - branches
