apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageoptimizer
spec:
  selector:
    matchLabels:
      app: imageoptimizer
  template:
    metadata:
      labels:
        app: imageoptimizer
    spec:
      containers:
        - name: imageoptimizer
          image: registry.lynx.agency/thepiconerd/imageoptimizer:IMAGE_TAG
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/src/app/cache
              name: cache
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: imageoptimizer
spec:
  type: NodePort
  selector:
    app: imageoptimizer
  ports:
    - port: 80
      targetPort: 80
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
