name: Docker Image CI

on: [release]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        printenv
        docker build . --tag imageoptimizer:latest
